# Generated by Django 6.0.4 on 2026-05-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('division', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Graphic Design', 'Graphic Design'), ('Video Editing', 'Video Editing'), ('PowerPoint', 'PowerPoint'), ('Photography', 'Photography'), ('Publication', 'Publication'), ('Web Design', 'Web Design')], max_length=100)),
                ('request_type', models.CharField(choices=[('PPT Presentation', 'PPT Presentation'), ('Tarp Design', 'Tarp Design'), ('Video Editing', 'Video Editing'), ('Certificate', 'Certificate'), ('Social Media Pubmat', 'Social Media Pubmat'), ('Newsletter', 'Newsletter')], max_length=100)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Requested', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
